<?php
//
//    ██   ██  ██████  ██████   ██████  ██    ██ ███    ██ ██████  ███████ 
//    ██   ██ ██       ██   ██ ██    ██ ██    ██ ████   ██ ██   ██ ██      
//    ███████ ██   ███ ██████  ██    ██ ██    ██ ██ ██  ██ ██   ██ ███████ 
//         ██ ██    ██ ██   ██ ██    ██ ██    ██ ██  ██ ██ ██   ██      ██ 
//         ██  ██████  ██   ██  ██████   ██████  ██   ████ ██████  ███████ 
//
//   DO NOT EDIT THIS FILE!
//   Instead, edit config.inc.php in this same directory.

$config['database_host'] = 'localhost';
$config['database_database'] = 'fourground';
$config['database_user'] = 'root';
$config['database_pass'] = '';

$config['use_recaptcha'] = false;
$config['recaptcha_secret'] = '';
$config['recaptcha_sitekey'] = '';

$config['debug_sql'] = false;
